/* create database and app login/user */
USE master;
GO

CREATE DATABASE [$(APP_DB)];
ALTER DATABASE [$(APP_DB)] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [$(APP_DB)] SET READ_COMMITTED_SNAPSHOT ON;
ALTER AUTHORIZATION ON DATABASE::[$(APP_DB)] TO sa;
GO

CREATE LOGIN [$(APP_USER)]
WITH
  PASSWORD=N'$(APP_PW)'
, DEFAULT_DATABASE=[$(APP_DB)]
, DEFAULT_LANGUAGE=us_english
, CHECK_EXPIRATION=OFF
, CHECK_POLICY=ON
;
GO

USE [$(APP_DB)];
GO

CREATE USER [$(APP_USER)] FOR LOGIN [$(APP_USER)] WITH DEFAULT_SCHEMA=dbo;
ALTER ROLE db_owner ADD MEMBER [$(APP_USER)];
GO
