name: Tests

on:
  push

jobs:

  # Generate one-time random passwords for MSSQL
  gen-passwords:
    runs-on: ubuntu-latest
    outputs:
      SAPW:  ${{ steps.genpw.outputs.sapw  }}
      APPPW: ${{ steps.genpw.outputs.apppw }}
    steps:
      - name: install pre-requisites
        run: sudo apt install --quiet --assume-yes apg
      - name: generate database passwords
        id: genpw
        run: |
          printf '::set-output name=sapw::%s\n' \
            $(apg -a 1 -n 1 -m 32 -M SNCL -E "~|@:;[]{}/()<>\\'\"")
          printf '::set-output name=apppw::%s\n' \
            $(apg -a 1 -n 1 -m 32 -M SNCL -E "~|@:;[]{}/()<>\\'\"")

  ms-test:

    runs-on: ubuntu-latest

    needs: gen-passwords
    env:
      SAPW:  ${{ needs.gen-passwords.outputs.SAPW  }}
      APPPW: ${{ needs.gen-passwords.outputs.APPPW }}
      SQLCMDSERVER: 127.0.0.1

    # Setup bare MSSQL database instance
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ${{ env.SAPW }}
          MSSQL_PID: Developer
          MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
        options: >-
          --name mssql
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -b -o /dev/null -S 127.0.0.1 -U sa -P '${MSSQL_SA_PASSWORD}' -Q 'SELECT 1;'"
          --health-interval 60s
          --health-timeout 30s
          --health-start-period 20s
          --health-retries 11
        ports:
        - 1433:1433

    steps:
      - name: show Docker processes
        run: docker ps --all
      - name: test connect to database as SA
        env:
          SQLCMDDBNAME: master
          SQLCMDUSER: sa
          SQLCMDPASSWORD: ${{ env.SAPW }}
        run: sqlcmd -b -m-1 -p1 -W -Q "SELECT
              ServerName = @@SERVERNAME
            , spid = @@SPID
            , login = SUSER_NAME()
            , DatabaseName = DB_NAME()
            , DBUser = USER_NAME()
          ;"
      - name: test reading env vars in sqlcmd
        env:
          SQLCMDDBNAME: master
          SQLCMDUSER: sa
          SQLCMDPASSWORD: ${{ env.SAPW }}
        run: sqlcmd -b -m-1 -p1 -W -Q "SELECT N'\$(APPPW)' AS app_password;"
      - uses: actions/checkout@v2
      - name: create database and login/user for app access
        env:
          APP_DB: myTestDB
          APP_PW: ${{ env.APPPW }}
          APP_USER: test_app_user
          SQLCMDDBNAME: master
          SQLCMDUSER: sa
          SQLCMDPASSWORD: ${{ env.SAPW }}
        run: sqlcmd -b -m-1 -p1 -W -i create_db.sql

# vim: set ts=2 sw=2 et si:
