name: Tests

on:
  push

jobs:

  ms-test:

    runs-on: ubuntu-latest

    env:
      APP_DB: myTestDB
      APP_USER: test_app_user
      # https://github.com/orgs/community/discussions/29880
      APP_PW: InsecureBecauseGitHubActionsDoNotSupportMaskedOutputs12#$
      SA_PW:  InsecureBecauseGitHubActionsDoNotSupportMaskedOutputs34%~
      SQLCMDSERVER: 127.0.0.1

    # Setup bare MSSQL database instance
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ${{ env.SA_PW }}
          MSSQL_PID: Developer
          MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
        options: >-
          --name mssql
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -b -o /dev/null -S 127.0.0.1 -U sa -P \"${MSSQL_SA_PASSWORD}\" -Q 'SELECT 1;'"
          --health-interval 60s
          --health-timeout 30s
          --health-start-period 20s
          --health-retries 5
        ports:
        - 1433:1433

    steps:
      - uses: actions/checkout@v2
      - name: create database and login/user for app access
        env:
          SQLCMDDBNAME: master
          SQLCMDUSER: sa
          SQLCMDPASSWORD: ${{ env.SA_PW }}
        run: sqlcmd -b -m-1 -p -i create_db.sql
      - name: test connect to app database using app login/user
        env:
          SQLCMDDBNAME: ${{ env.APP_DB }}
          SQLCMDUSER: ${{ env.APP_USER }}
          SQLCMDPASSWORD: ${{ env.APP_PW }}
        run: sqlcmd -b -m-1 -p -W -Q "SELECT
              ServerName = @@SERVERNAME
            , spid = @@SPID
            , login = SUSER_NAME()
            , DatabaseName = DB_NAME()
            , DBUser = USER_NAME()
          ;"

# vim: set ts=2 sw=2 et si:
